#配置数据库名称--必须配置
database-name: test

spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  datasource:
    url: jdbc:mysql://192.168.22.130:3306/${database-name}?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    cache-enabled: false

